chrome.storage.sync.set({'companies':companies});

chrome.runtime.onMessage.addListener(function(request, sender, sendResponse){
    if(request.todo == "showPageAction"){
        chrome.tabs.query({active:true,currentWindow:true},function(tabs){
            chrome.pageAction.show(tabs[0].id);
        });
    }
})
//basic company data provided by forbes top 2000 list 2019
var companies = [
{name:"Google",country:"United States"},
{name:"JPMorgan Chase",country:"United States"},
{name:"Bank of America",country:"United States"},
{name:"Apple",country:"United States"},
{name:"Wells Fargo",country:"United States"},
{name:"AT&T",country:"United States"},
{name:"Samsung Electronics",country:"South Korea"},
{name:"Citigroup",country:"United States"},
{name:"Toyota Motor",country:"Japan"},
{name:"Microsoft",country:"United States"},
{name:"Alphabet",country:"United States"},
{name:"Volkswagen Group",country:"Germany"},
{name:"Verizon Communications",country:"United States"},
{name:"Allianz",country:"Germany"},
{name:"BP",country:"United Kingdom"},
{name:"Total",country:"France"},
{name:"Berkshire Hathaway",country:"United States"},
{name:"China Mobile",country:"Hong Kong"},
{name:"Amazon",country:"United States"},
{name:"Walmart",country:"United States"},
{name:"Santander",country:"Spain"},
{name:"China Merchants Bank",country:"China"},
{name:"UnitedHealth Group",country:"United States"},
{name:"Comcast",country:"United States"},
{name:"BNP Paribas",country:"France"},
{name:"Sinopec",country:"China"},
{name:"Softbank",country:"Japan"},
{name:"Daimler",country:"Germany"},
{name:"Johnson & Johnson",country:"United States"},
{name:"Bank of Communications",country:"China"},
{name:"Gazprom",country:"Russia"},
{name:"RBC",country:"Canada"},
{name:"Nestle",country:"Switzerland"},
{name:"Mitsubishi UFJ Financial",country:"Japan"},
{name:"Intel",country:"United States"},
{name:"Goldman Sachs Group",country:"United States"},
{name:"TD Bank Group",country:"Canada"},
{name:"Sberbank",country:"Russia"},
{name:"Morgan Stanley",country:"United States"},
{name:"Boeing",country:"United States"},
{name:"Petrobras",country:"Brazil"},
{name:"Nippon Telegraph & Tel",country:"Japan"},
{name:"Rosneft",country:"Russia"},
{name:"Procter & Gamble",country:"United States"},
{name:"Pfizer",country:"United States"},
{name:"Industrial Bank",country:"China"},
{name:"General Motors",country:"United States"},
{name:"BMW Group",country:"Germany"},
{name:"Itaú Unibanco Holding",country:"Brazil"},
{name:"Alibaba",country:"China"},
{name:"IBM",country:"United States"},
{name:"Novartis",country:"Switzerland"},
{name:"Postal Savings Bank Of China (PSBC)",country:"China"},
{name:"Facebook",country:"United States"},
{name:"Siemens",country:"Germany"},
{name:"Shanghai Pudong Development",country:"China"},
{name:"Japan Post Holdings",country:"Japan"},
{name:"Sumitomo Mitsui Financial",country:"Japan"},
{name:"Banco Bradesco",country:"Brazil"},
{name:"Anheuser-Busch InBev",country:"Belgium"},
{name:"Walt Disney",country:"United States"},
{name:"Reliance Industries",country:"India"},
{name:"CITIC",country:"Hong Kong"},
{name:"Sony",country:"Japan"},
{name:"Cisco Systems",country:"United States"},
{name:"Tencent Holdings",country:"China"},
{name:"Honda Motor",country:"Japan"},
{name:"Enel",country:"Italy"},
{name:"United Technologies",country:"United States"},
{name:"Commonwealth Bank",country:"Australia"},
{name:"China State Construction Engineering",country:"China"},
{name:"DowDuPont",country:"United States"},
{name:"Equinor",country:"Norway"},
{name:"American Express",country:"United States"},
{name:"MetLife",country:"United States"},
{name:"AXA Group",country:"France"},
{name:"PepsiCo",country:"United States"},
{name:"Bank of Nova Scotia",country:"Canada"},
{name:"Roche Holding",country:"Switzerland"},
{name:"ING Group",country:"Netherlands"},
{name:"Lloyds Banking Group",country:"United Kingdom"},
{name:"Eni",country:"Italy"},
{name:"Oracle",country:"United States"},
{name:"China Citic Bank",country:"China"},
{name:"China Evergrande Group",country:"China"},
{name:"UBS",country:"Switzerland"},
{name:"AIRBUS",country:"Netherlands"},
{name:"LukOil",country:"Russia"},
{name:"Prudential Financial",country:"United States"},
{name:"BASF",country:"Germany"},
{name:"SAIC Motor",country:"China"},
{name:"Westpac Banking Group",country:"Australia"},
{name:"British American Tobacco",country:"United Kingdom"},
{name:"US Bancorp",country:"United States"},
{name:"Credit Agricole",country:"France"},
{name:"China Life Insurance",country:"China"},
{name:"Unilever",country:"Netherlands"},
{name:"Glencore International",country:"Switzerland"},
{name:"Mitsubishi",country:"Japan"},
{name:"BHP Group",country:"Australia"},
{name:"Ford Motor",country:"United States"},
{name:"Rio Tinto",country:"United Kingdom"},
{name:"Prudential",country:"United Kingdom"},
{name:"AIA Group",country:"Hong Kong"},
{name:"China Minsheng Banking",country:"China"},
{name:"Sanofi",country:"France"},
{name:"Deutsche Telekom",country:"Germany"},
{name:"Zurich Insurance Group",country:"Switzerland"},
{name:"Brookfield Asset Management",country:"Canada"},
{name:"Merck & Co.",country:"United States"},
{name:"ANZ",country:"Australia"},
{name:"Caterpillar",country:"United States"},
{name:"Saudi Basic Industries",country:"Saudi Arabia"},
{name:"Hon Hai Precision",country:"Taiwan"},
{name:"China Vanke",country:"China"},
{name:"Mizuho Financial",country:"Japan"},
{name:"CNOOC",country:"Hong Kong"},
{name:"Home Depot",country:"United States"},
{name:"Taiwan Semiconductor",country:"Taiwan"},
{name:"Country Garden Holdings",country:"China"},
{name:"Capital One Financial",country:"United States"},
{name:"Intesa Sanpaolo",country:"Italy"},
{name:"Nissan Motor",country:"Japan"},
{name:"Coca-Cola",country:"United States"},
{name:"Bank of Montreal",country:"Canada"},
{name:"BBVA-Banco Bilbao Vizcaya",country:"Spain"},
{name:"Walgreens Boots Alliance",country:"United States"},
{name:"Chubb",country:"Switzerland"},
{name:"NAB - National Australia Bank",country:"Australia"},
{name:"Vale",country:"Brazil"},
{name:"China Pacific Insurance",country:"China"},
{name:"Anthem",country:"United States"},
{name:"Telefónica",country:"Spain"},
{name:"Christian Dior",country:"France"},
{name:"Generali Group",country:"Italy"},
{name:"Iberdrola",country:"Spain"},
{name:"PNC Financial Services",country:"United States"},
{name:"GlaxoSmithKline",country:"United Kingdom"},
{name:"Munich Re",country:"Germany"},
{name:"Cigna",country:"United States"},
{name:"Medtronic",country:"Ireland"},
{name:"China Everbright Bank",country:"China"},
{name:"China Shenhua Energy",country:"China"},
{name:"Honeywell International",country:"United States"},
{name:"Banco do Brasil",country:"Brazil"},
{name:"People's Insurance",country:"China"},
{name:"UniCredit",country:"Italy"},
{name:"CK Hutchison",country:"Hong Kong"},
{name:"Société Générale",country:"France"},
{name:"ConocoPhillips",country:"United States"},
{name:"United Parcel Service",country:"United States"},
{name:"VINCI",country:"France"},
{name:"Visa",country:"United States"},
{name:"Tokio Marine Holdings",country:"Japan"},
{name:"Bayer",country:"Germany"},
{name:"PTT PCL",country:"Thailand"},
{name:"Manulife",country:"Canada"},
{name:"AbbVie",country:"United States"},
{name:"China Telecom",country:"China"},
{name:"Phillips 66",country:"United States"},
{name:"KDDI",country:"Japan"},
{name:"Fiat Chrysler Automobiles",country:"United Kingdom"},
{name:"Marathon Petroleum",country:"United States"},
{name:"Costco Wholesale",country:"United States"},
{name:"Enbridge",country:"Canada"},
{name:"Amgen",country:"United States"},
{name:"SAP",country:"Germany"},
{name:"Bank of New York Mellon",country:"United States"},
{name:"Broadcom",country:"United States"},
{name:"SK Hynix",country:"South Korea"},
{name:"China Communications Construction",country:"China"},
{name:"Lockheed Martin",country:"United States"},
{name:"Itochu",country:"Japan"},
{name:"Duke Energy",country:"United States"},
{name:"FedEx",country:"United States"},
{name:"Royal Bank of Scotland",country:"United Kingdom"},
{name:"Orange",country:"France"},
{name:"Barclays",country:"United Kingdom"},
{name:"Union Pacific",country:"United States"},
{name:"América Móvil",country:"Mexico"},
{name:"Canadian Imperial Bank",country:"Canada"},
{name:"Credit Suisse Group",country:"Switzerland"},
{name:"Synchrony Financial",country:"United States"},
{name:"United States",country:"undefined"},
{name:"NextEra Energy",country:"United States"},
{name:"Deere & Company",country:"United States"},
{name:"ArcelorMittal",country:"Luxembourg"},
{name:"Mitsui",country:"Japan"},
{name:"Abbott Laboratories",country:"United States"},
{name:"China Railway Group",country:"China"},
{name:"Gilead Sciences",country:"United States"},
{name:"China Railway Construction",country:"China"},
{name:"L'Oréal",country:"France"},
{name:"Exelon",country:"United States"},
{name:"Delta Air Lines",country:"United States"},
{name:"Renault",country:"France"},
{name:"Charter Communications",country:"United States"},
{name:"Micron Technology",country:"United States"},
{name:"Qatar National Bank",country:"Qatar"},
{name:"Deutsche Post",country:"Germany"},
{name:"HDFC Bank",country:"India"},
{name:"Altria Group",country:"United States"},
{name:"Valero Energy",country:"United States"},
{name:"Philip Morris International",country:"United States"},
{name:"DBS",country:"Singapore"},
{name:"BlackRock",country:"United States"},
{name:"Southern Company",country:"United States"},
{name:"3M",country:"United States"},
{name:"Schlumberger",country:"United States"},
{name:"Peugeot",country:"France"},
{name:"Linde",country:"United Kingdom"},
{name:"Oil & Natural Gas",country:"India"},
{name:"Dai-ichi Life Insurance",country:"Japan"},
{name:"Thermo Fisher Scientific",country:"United States"},
{name:"Aflac",country:"United States"},
{name:"Allstate",country:"United States"},
{name:"Hyundai Motor",country:"South Korea"},
{name:"Travelers",country:"United States"},
{name:"ENGIE",country:"France"},
{name:"Mondelēz International",country:"United States"},
{name:"Suncor Energy",country:"Canada"},
{name:"Hitachi",country:"Japan"},
{name:"Nordea Bank",country:"Sweden"},
{name:"Aviva",country:"United Kingdom"},
{name:"Target",country:"United States"},
{name:"Lowe's",country:"United States"},
{name:"General Dynamics",country:"United States"},
{name:"Repsol",country:"Spain"},
{name:"AstraZeneca",country:"United Kingdom"},
{name:"Eli Lilly",country:"United States"},
{name:"Continental",country:"Germany"},
{name:"Charles Schwab",country:"United States"},
{name:"National Grid",country:"United Kingdom"},
{name:"Progressive",country:"United States"},
{name:"Tesco",country:"United Kingdom"},
{name:"Danone",country:"France"},
{name:"Poly Developments & Holdings Group",country:"China"},
{name:"Volvo Group",country:"Sweden"},
{name:"HCA Healthcare",country:"United States"},
{name:"Accenture",country:"Ireland"},
{name:"Central Japan Railway",country:"Japan"},
{name:"East Japan Railway",country:"Japan"},
{name:"China Unicom",country:"Hong Kong"},
{name:"Schneider Electric",country:"France"},
{name:"Midea Group",country:"China"},
{name:"KBC Group",country:"Belgium"},
{name:"McDonald's",country:"United States"},
{name:"Denso",country:"Japan"},
{name:"JXTG Holdings",country:"Japan"},
{name:"Fresenius",country:"Germany"},
{name:"BB&T",country:"United States"},
{name:"Gree Electric Appliances",country:"China"},
{name:"Anglo American",country:"United Kingdom"},
{name:"Møller-Maersk",country:"Denmark"},
{name:"E.ON",country:"Germany"},
{name:"MS&AD Insurance",country:"Japan"},
{name:"Huaxia Bank",country:"China"},
{name:"Bristol-Myers Squibb",country:"United States"},
{name:"China Resources Land",country:"Hong Kong"},
{name:"Air Liquide",country:"France"},
{name:"EDF",country:"France"},
{name:"Baoshan Iron & Steel",country:"China"},
{name:"Danaher",country:"United States"},
{name:"Legal & General Group",country:"United Kingdom"},
{name:"EXOR",country:"Netherlands"},
{name:"Sun Life Financial",country:"Canada"},
{name:"BT Group",country:"United Kingdom"},
{name:"KB Financial Group",country:"South Korea"},
{name:"Northrop Grumman",country:"United States"},
{name:"Seven & I Holdings",country:"Japan"},
{name:"HP",country:"United States"},
{name:"Nike",country:"United States"},
{name:"Shinhan Financial Group",country:"South Korea"},
{name:"ABB",country:"Switzerland"},
{name:"Diageo",country:"United Kingdom"},
{name:"Bank of Beijing",country:"China"},
{name:"CNP Assurances",country:"France"},
{name:"Japan Tobacco",country:"Japan"},
{name:"Oversea-Chinese Banking",country:"Singapore"},
{name:"Indian Oil",country:"India"},
{name:"Inditex",country:"Spain"},
{name:"Dominion Resources",country:"United States"},
{name:"Sumitomo",country:"Japan"},
{name:"Occidental Petroleum",country:"United States"},
{name:"Reckitt Benckiser Group",country:"United Kingdom"},
{name:"CRRC",country:"China"},
{name:"Cathay Financial",country:"Taiwan"},
{name:"Kroger",country:"United States"},
{name:"Baidu",country:"China"},
{name:"Panasonic",country:"Japan"},
{name:"Johnson Controls International",country:"Ireland"},
{name:"Ecopetrol",country:"Colombia"},
{name:"Canon",country:"Japan"},
{name:"Royal Ahold Delhaize N.V.",country:"Netherlands"},
{name:"Jardine Matheson",country:"Hong Kong"},
{name:"Raytheon",country:"United States"},
{name:"Sunac China Holdings",country:"China"},
{name:"United Continental Holdings",country:"United States"},
{name:"United Overseas Bank",country:"Singapore"},
{name:"Nippon Steel",country:"Japan"},
{name:"LyondellBasell Industries",country:"United Kingdom"},
{name:"Qualcomm",country:"United States"},
{name:"Safran",country:"France"},
{name:"Carnival",country:"United States"},
{name:"SK Holdings",country:"South Korea"},
{name:"State Street",country:"United States"},
{name:"Orix",country:"Japan"},
{name:"Celgene",country:"United States"},
{name:"American Electric",country:"United States"},
{name:"PayPal",country:"United States"},
{name:"EOG Resources",country:"United States"},
{name:"Greenland Holdings Group",country:"China"},
{name:"LafargeHolcim",country:"Switzerland"},
{name:"Henkel",country:"Germany"},
{name:"Posco",country:"South Korea"},
{name:"Natixis",country:"France"},
{name:"Mitsubishi Electric",country:"Japan"},
{name:"Bridgestone",country:"Japan"},
{name:"Archer Daniels Midland",country:"United States"},
{name:"Sun Hung Kai Properties",country:"Hong Kong"},
{name:"Toshiba",country:"Japan"},
{name:"Surgutneftegas",country:"Russia"},
{name:"Poste Italiane",country:"Italy"},
{name:"HDFC",country:"India"},
{name:"First Abu Dhabi Bank",country:"United Arab Emirates"},
{name:"Mastercard",country:"United States"},
{name:"Kinder Morgan",country:"United States"},
{name:"New China Life Insurance",country:"China"},
{name:"DNB",country:"Norway"},
{name:"SunTrust Banks",country:"United States"},
{name:"Danske Bank",country:"Denmark"},
{name:"Discover Financial Services",country:"United States"},
{name:"BCE",country:"Canada"},
{name:"Canadian Natural Resources",country:"Canada"},
{name:"CaixaBank",country:"Spain"},
{name:"CSX",country:"United States"},
{name:"Longfor Group Holdings",country:"China"},
{name:"TransCanada",country:"Canada"},
{name:"Bank Of Shanghai",country:"China"},
{name:"Macquarie Group",country:"Australia"},
{name:"Fubon Financial",country:"Taiwan"},
{name:"Marubeni",country:"Japan"},
{name:"Starbucks",country:"United States"},
{name:"Fannie Mae",country:"United States"},
{name:"Samsung Life Insurance",country:"South Korea"},
{name:"Tyson Foods",country:"United States"},
{name:"Becton Dickinson",country:"United States"},
{name:"Automatic Data Processing",country:"United States"},
{name:"Humana",country:"United States"},
{name:"Standard Chartered",country:"United Kingdom"},
{name:"Imperial Brands",country:"United Kingdom"},
{name:"Richemont",country:"Switzerland"},
{name:"Eaton",country:"Ireland"},
{name:"Kering",country:"France"},
{name:"Bank Rakyat Indonesia (BRI)",country:"Indonesia"},
{name:"Couche Tard",country:"Canada"},
{name:"Saudi Telecom",country:"Saudi Arabia"},
{name:"Stryker",country:"United States"},
{name:"Freddie Mac",country:"United States"},
{name:"Daiwa House Industry",country:"Japan"},
{name:"Heineken",country:"Netherlands"},
{name:"Booking Holdings",country:"United States"},
{name:"NN Group",country:"Netherlands"},
{name:"Ameriprise Financial",country:"United States"},
{name:"American Airlines Group",country:"United States"},
{name:"Tata Consultancy Services",country:"India"},
{name:"Mitsui Fudosan",country:"Japan"},
{name:"Novo Nordisk",country:"Denmark"},
{name:"Takeda Pharmaceutical",country:"Japan"},
{name:"Maybank",country:"Malaysia"},
{name:"China Merchants Shekou Industrial Zone Holdings",country:"China"},
{name:"Norfolk Southern",country:"United States"},
{name:"Power Construction Corporation of China",country:"China"},
{name:"Michelin Group",country:"France"},
{name:"EssilorLuxottica",country:"France"},
{name:"Etisalat",country:"United Arab Emirates"},
{name:"CRH",country:"Ireland"},
{name:"Lincoln National",country:"United States"},
{name:"Transneft",country:"Russia"},
{name:"Canadian National Railway",country:"Canada"},
{name:"General Electric",country:"United States"},
{name:"Hyundai Mobis",country:"South Korea"},
{name:"Erste Group Bank",country:"Austria"},
{name:"Swiss Life Holding",country:"Switzerland"},
{name:"ASML Holding",country:"Netherlands"},
{name:"Komatsu",country:"Japan"},
{name:"Suzuki Motor",country:"Japan"},
{name:"TJX Cos",country:"United States"},
{name:"Power Corp of Canada",country:"Canada"},
{name:"Southwest Airlines",country:"United States"},
{name:"Telstra",country:"Australia"},
{name:"ICICI Bank",country:"India"},
{name:"Freeport-McMoRan",country:"United States"},
{name:"Texas Instruments",country:"United States"},
{name:"Sompo",country:"Japan"},
{name:"Principal Financial Group",country:"United States"},
{name:"OMV Group",country:"Austria"},
{name:"Shin-Etsu Chemical",country:"Japan"},
{name:"Anhui Conch Cement",country:"China"},
{name:"Hartford Financial Services",country:"United States"},
{name:"SingTel",country:"Singapore"},
{name:"CVS Health",country:"United States"},
{name:"Marriott International",country:"United States"},
{name:"AmerisourceBergen",country:"United States"},
{name:"Deutsche Lufthansa",country:"Germany"},
{name:"Tokyo Electric Power",country:"Japan"},
{name:"Standard Bank Group",country:"South Africa"},
{name:"Fosun International",country:"China"},
{name:"SEB AB",country:"Sweden"},
{name:"Naspers",country:"South Africa"},
{name:"Kweichow Moutai",country:"China"},
{name:"National Commercial Bank",country:"Saudi Arabia"},
{name:"Bank Of Jiangsu",country:"China"},
{name:"Biogen",country:"United States"},
{name:"Suning.com",country:"China"},
{name:"Bouygues",country:"France"},
{name:"Wilmar International",country:"Singapore"},
{name:"Xiaomi",country:"China"},
{name:"Magna International",country:"Canada"},
{name:"International Airlines",country:"United Kingdom"},
{name:"Femsa",country:"Mexico"},
{name:"Adidas",country:"Germany"},
{name:"Netflix",country:"United States"},
{name:"Philips",country:"Netherlands"},
{name:"Sumitomo Mitsui Trust",country:"Japan"},
{name:"China Yangtze Power",country:"China"},
{name:"Applied Materials",country:"United States"},
{name:"Paccar",country:"United States"},
{name:"Sysco",country:"United States"},
{name:"Larsen & Toubro",country:"India"},
{name:"Emerson Electric",country:"United States"},
{name:"Samsung C&T",country:"South Korea"},
{name:"International Paper",country:"United States"},
{name:"Halliburton",country:"United States"},
{name:"China Cinda Asset Management",country:"China"},
{name:"Daikin Industries",country:"Japan"},
{name:"FirstRand",country:"South Africa"},
{name:"Salesforce.com",country:"United States"},
{name:"KIA Motors",country:"South Korea"},
{name:"CK Asset Holdings",country:"Hong Kong"},
{name:"Consolidated Edison",country:"United States"},
{name:"Svenska Handelsbanken",country:"Sweden"},
{name:"Swire Pacific",country:"Hong Kong"},
{name:"General Mills",country:"United States"},
{name:"CTBC Financial",country:"Taiwan"},
{name:"SK Innovation",country:"South Korea"},
{name:"Pernod Ricard",country:"France"},
{name:"Citic Securities",country:"China"},
{name:"New World Development",country:"Hong Kong"},
{name:"Waste Management",country:"United States"},
{name:"Sempra Energy",country:"United States"},
{name:"Aegon",country:"Netherlands"},
{name:"State Bank of India",country:"India"},
{name:"American International Group",country:"United States"},
{name:"Toyota Industries",country:"Japan"},
{name:"Vodafone",country:"United Kingdom"},
{name:"Sampo",country:"Finland"},
{name:"Subaru",country:"Japan"},
{name:"IntercontinentalExchange",country:"United States"},
{name:"LG Chem",country:"South Korea"},
{name:"Fifth Third Bank",country:"United States"},
{name:"Dell Technologies",country:"United States"},
{name:"SK Telecom",country:"South Korea"},
{name:"VTB Bank",country:"Russia"},
{name:"Banorte",country:"Mexico"},
{name:"Swiss Re",country:"Switzerland"},
{name:"Mitsubishi Chemical",country:"Japan"},
{name:"Centene",country:"United States"},
{name:"BAE Systems",country:"United States"},
{name:"Hana Financial Group",country:"South Korea"},
{name:"Fast Retailing",country:"Japan"},
{name:"CNH Industrial",country:"United Kingdom"},
{name:"Bank Mandiri",country:"Indonesia"},
{name:"HeidelbergCement",country:"Germany"},
{name:"Hewlett Packard Enterprise",country:"United States"},
{name:"Talanx",country:"Germany"},
{name:"Cummins",country:"United States"},
{name:"Orsted",country:"Denmark"},
{name:"WPP",country:"United Kingdom"},
{name:"Marsh & McLennan",country:"United States"},
{name:"Grupo ACS",country:"Spain"},
{name:"Xcel Energy",country:"United States"},
{name:"Las Vegas Sands",country:"United States"},
{name:"NTPC",country:"India"},
{name:"China Zheshang Bank",country:"China"},
{name:"Commerzbank",country:"Germany"},
{name:"Toyota Tsusho",country:"Japan"},
{name:"Lennar",country:"United States"},
{name:"Swedbank",country:"Sweden"},
{name:"Compass Group",country:"United Kingdom"},
{name:"Woolworths",country:"Australia"},
{name:"Novatek",country:"Russia"},
{name:"National Bank of Canada",country:"Canada"},
{name:"LG Electronics",country:"South Korea"},
{name:"Thales",country:"France"},
{name:"Public Service Enterprise Group",country:"United States"},
{name:"Adobe",country:"United States"},
{name:"China Taiping Insurance",country:"Hong Kong"},
{name:"TE Connectivity",country:"Switzerland"},
{name:"Mitsubishi Estate",country:"Japan"},
{name:"Metallurgical Corp of China",country:"China"},
{name:"Emirates NBD",country:"United Arab Emirates"},
{name:"Kansai Electric Power",country:"Japan"},
{name:"Ecolab",country:"United States"},
{name:"DXC Technology",country:"United States"},
{name:"M&T Bank",country:"United States"},
{name:"Fujitsu",country:"Japan"},
{name:"Constellation Brands",country:"United States"},
{name:"Wesfarmers",country:"Australia"},
{name:"CLP Holdings",country:"Hong Kong"},
{name:"Al Rajhi Bank",country:"Saudi Arabia"},
{name:"Asahi Group Holdings",country:"Japan"},
{name:"Illinois Tool Works",country:"United States"},
{name:"Fujifilm Holdings",country:"Japan"},
{name:"Saint-Gobain",country:"France"},
{name:"Cognizant",country:"United States"},
{name:"Tatneft",country:"Russia"},
{name:"DTE Energy",country:"United States"},
{name:"KeyCorp",country:"United States"},
{name:"Recruit Holdings",country:"Japan"},
{name:"NVIDIA",country:"United States"},
{name:"Sasol",country:"South Africa"},
{name:"JFE Holdings",country:"Japan"},
{name:"Bank of Ningbo",country:"China"},
{name:"eBay",country:"United States"},
{name:"Mitsubishi Heavy Industries",country:"Japan"},
{name:"Citizens Financial Group",country:"United States"},
{name:"Weichai Power",country:"China"},
{name:"Nucor",country:"United States"},
{name:"Sherwin-Williams",country:"United States"},
{name:"Formosa Petrochemical",country:"Taiwan"},
{name:"Ally Financial",country:"United States"},
{name:"Murata Manufacturing",country:"Japan"},
{name:"Northern Trust",country:"United States"},
{name:"American Tower",country:"United States"},
{name:"China Fortune Land Development",country:"China"},
{name:"CME Group",country:"United States"},
{name:"Samsung Fire & Marine",country:"South Korea"},
{name:"Deutsche Bank",country:"Germany"},
{name:"Kraft Heinz Company",country:"United States"},
{name:"Qingdao Haier",country:"China"},
{name:"Associated British Foods",country:"United Kingdom"},
{name:"MTR",country:"Hong Kong"},
{name:"Tata Steel",country:"India"},
{name:"Bank Central Asia",country:"Indonesia"},
{name:"Bank of Nanjing",country:"China"},
{name:"Telenor",country:"Norway"},
{name:"Colgate-Palmolive",country:"United States"},
{name:"Boston Scientific",country:"United States"},
{name:"Kimberly-Clark",country:"United States"},
{name:"China National Building",country:"China"},
{name:"CBS",country:"United States"},
{name:"Dollar General",country:"United States"},
{name:"DISH Network",country:"United States"},
{name:"Keurig Dr Pepper",country:"United States"},
{name:"Kubota",country:"Japan"},
{name:"Rakuten",country:"Japan"},
{name:"Merck",country:"Germany"},
{name:"Rogers Communications",country:"Canada"},
{name:"PPL",country:"United States"},
{name:"Aisin Seiki",country:"Japan"},
{name:"Aroundtown",country:"Luxembourg"},
{name:"Luxembourg",country:"undefined"},
{name:"Aon",country:"United Kingdom"},
{name:"Sinopharm Group",country:"China"},
{name:"Royal Caribbean Cruises",country:"United States"},
{name:"Norilsk Nickel",country:"Russia"},
{name:"Woori Financial Group",country:"South Korea"},
{name:"Kirin Holdings",country:"Japan"},
{name:"NXP Semiconductors",country:"Netherlands"},
{name:"Saudi Electricity",country:"Saudi Arabia"},
{name:"Swisscom",country:"Switzerland"},
{name:"McKesson",country:"United States"},
{name:"Nidec",country:"Japan"},
{name:"Omnicom Group",country:"United States"},
{name:"Coal India",country:"India"},
{name:"RELX",country:"United Kingdom"},
{name:"Ingersoll Rand",country:"Ireland"},
{name:"FirstEnergy",country:"United States"},
{name:"Anadarko Petroleum",country:"United States"},
{name:"Korea Electric Power",country:"South Korea"},
{name:"Regions Financial",country:"United States"},
{name:"Simon Property Group",country:"United States"},
{name:"Corning",country:"United States"},
{name:"The Estée Lauder Companies",country:"United States"},
{name:"Henderson Land",country:"Hong Kong"},
{name:"Grupo Mexico",country:"Mexico"},
{name:"Allergan",country:"Ireland"},
{name:"H&M - Hennes & Mauritz",country:"Sweden"},
{name:"Loews",country:"United States"},
{name:"VMware",country:"United States"},
{name:"Best Buy",country:"United States"},
{name:"First Data",country:"United States"},
{name:"Air Products & Chemicals",country:"United States"},
{name:"Astellas Pharma",country:"Japan"},
{name:"Asahi Kasei",country:"Japan"},
{name:"Entergy",country:"United States"},
{name:"Ageas",country:"Belgium"},
{name:"PPG",country:"United States"},
{name:"Shimao Property Holdings",country:"Hong Kong"},
{name:"Sumitomo Electric",country:"Japan"},
{name:"Formosa Chemicals",country:"Taiwan"},
{name:"Atlantia",country:"Italy"},
{name:"Kotak Mahindra Bank",country:"India"},
{name:"Tenaga Nasional",country:"Malaysia"},
{name:"JD.com",country:"China"},
{name:"Wheelock",country:"Hong Kong"},
{name:"Western Digital",country:"United States"},
{name:"Industrial Bank of Korea",country:"South Korea"},
{name:"Baxter International",country:"United States"},
{name:"Dongfeng Motor Group",country:"China"},
{name:"Nintendo",country:"Japan"},
{name:"Aeon",country:"Japan"},
{name:"Coca-Cola European Partners",country:"United Kingdom"},
{name:"Vonovia",country:"Germany"},
{name:"Teck Resources",country:"Canada"},
{name:"Evonik",country:"Germany"},
{name:"TELUS",country:"Canada"},
{name:"RWE Group",country:"Germany"},
{name:"Devon Energy",country:"United States"},
{name:"Bharat Petroleum",country:"India"},
{name:"Eversource Energy",country:"United States"},
{name:"Oneok",country:"United States"},
{name:"TD Ameritrade Holding",country:"United States"},
{name:"Siam Commercial Bank",country:"Thailand"},
{name:"Edp-energias De Portugal",country:"Portugal"},
{name:"Resona Holdings",country:"Japan"},
{name:"Sumitomo Realty",country:"Japan"},
{name:"Raiffeisen Bank International",country:"Austria"},
{name:"Daqin Railway",country:"China"},
{name:"Idemitsu Kosan",country:"Japan"},
{name:"Unibail-Rodamco",country:"Netherlands"},
{name:"Parker-Hannifin",country:"United States"},
{name:"BOE Technology Group",country:"China"},
{name:"Nokia",country:"Finland"},
{name:"Infosys",country:"India"},
{name:"Public Bank",country:"Malaysia"},
{name:"Kao",country:"Japan"},
{name:"Mapfre",country:"Spain"},
{name:"Geely Automobile Holdings",country:"Hong Kong"},
{name:"Siam Cement",country:"Thailand"},
{name:"Nan Ya Plastics",country:"Taiwan"},
{name:"PKN Orlen",country:"Poland"},
{name:"Naturgy Energy Group",country:"Spain"},
{name:"Kellogg",country:"United States"},
{name:"WEC Energy Group",country:"United States"},
{name:"CNPC Capital",country:"China"},
{name:"Kyocera",country:"Japan"},
{name:"Telia",country:"Sweden"},
{name:"Eletrobrás",country:"Brazil"},
{name:"Guangzhou Automobile Group",country:"China"},
{name:"CIMB Group Holdings",country:"Malaysia"},
{name:"Prologis",country:"United States"},
{name:"Absa Group",country:"South Africa"},
{name:"Sodexo",country:"France"},
{name:"Isbank",country:"Turkey"},
{name:"Carrefour",country:"France"},
{name:"Republic Services",country:"United States"},
{name:"Publicis Groupe",country:"France"},
{name:"Porsche Automobil Holding",country:"Germany"},
{name:"D.R. Horton",country:"United States"},
{name:"Kasikornbank",country:"Thailand"},
{name:"Capgemini",country:"France"},
{name:"Ross Stores",country:"United States"},
{name:"Deutsche Boerse",country:"Germany"},
{name:"Grupo Aval",country:"Colombia"},
{name:"Husky Energy",country:"Canada"},
{name:"CGN Power",country:"China"},
{name:"West Japan Railway",country:"Japan"},
{name:"Legend Holding",country:"China"},
{name:"Nutrien",country:"Canada"},
{name:"Activision Blizzard",country:"United States"},
{name:"Toray Industries",country:"Japan"},
{name:"Chubu Electric Power",country:"Japan"},
{name:"China Tower Corp.",country:"China"},
{name:"Analog Devices",country:"United States"},
{name:"Grupa PZU",country:"Poland"},
{name:"Viacom",country:"United States"},
{name:"Fidelity National Information",country:"United States"},
{name:"Sekisui House",country:"Japan"},
{name:"Akzo Nobel",country:"Netherlands"},
{name:"Huntington Bank",country:"United States"},
{name:"WH Group",country:"Hong Kong"},
{name:"Molson Coors Brewing",country:"United States"},
{name:"Haitong Securities",country:"China"},
{name:"AES",country:"United States"},
{name:"Tesla",country:"United States"},
{name:"Falabella",country:"Chile"},
{name:"Fox",country:"United States"},
{name:"Veolia Environnement",country:"France"},
{name:"Link REIT",country:"Hong Kong"},
{name:"Lenovo Group",country:"Hong Kong"},
{name:"Atlas Copco",country:"Sweden"},
{name:"Suncorp Group",country:"Australia"},
{name:"All Nippon Airways",country:"Japan"},
{name:"T&D Holdings",country:"Japan"},
{name:"Lam Research",country:"United States"},
{name:"Pioneer Natural Resources",country:"United States"},
{name:"Vivendi",country:"France"},
{name:"VF",country:"United States"},
{name:"Solvay",country:"Belgium"},
{name:"UPM-Kymmene",country:"Finland"},
{name:"Uniper",country:"Germany"},
{name:"National Bank of Kuwait",country:"Kuwait"},
{name:"Samba Financial Group",country:"Saudi Arabia"},
{name:"China Southern Airlines",country:"China"},
{name:"Nomura",country:"Japan"},
{name:"Reinsurance Group of America",country:"United States"},
{name:"Eiffage",country:"France"},
{name:"Cardinal Health",country:"United States"},
{name:"Crown Castle International",country:"United States"},
{name:"Ericsson",country:"Sweden"},
{name:"Sumitomo Chemical",country:"Japan"},
{name:"Tokyo Electron",country:"Japan"},
{name:"Willis Towers Watson",country:"United Kingdom"},
{name:"CBRE Group",country:"United States"},
{name:"Essity Ab",country:"Sweden"},
{name:"Sandvik",country:"Sweden"},
{name:"CSL",country:"Australia"},
{name:"Credicorp",country:"Peru"},
{name:"Riyad Bank",country:"Saudi Arabia"},
{name:"London Stock Exchange",country:"United Kingdom"},
{name:"Guotai Junan Securities",country:"China"},
{name:"DSM",country:"Netherlands"},
{name:"Bancolombia",country:"Colombia"},
{name:"Rolls-Royce Holdings",country:"United Kingdom"},
{name:"Hong Kong Exchanges",country:"Hong Kong"},
{name:"Otsuka Holding",country:"Japan"},
{name:"Stanley Black & Decker",country:"United States"},
{name:"BYD",country:"China"},
{name:"WestRock",country:"United States"},
{name:"CarMax",country:"United States"},
{name:"Aptiv",country:"Ireland"},
{name:"Axis Bank",country:"India"},
{name:"CenturyLink",country:"United States"},
{name:"Fortive",country:"United States"},
{name:"George Weston",country:"Canada"},
{name:"Koç Holding",country:"Turkey"},
{name:"Huaneng Power International",country:"China"},
{name:"Isuzu Motors",country:"Japan"},
{name:"Telkom Indonesia",country:"Indonesia"},
{name:"China Energy Engineering",country:"China"},
{name:"Unipol Gruppo",country:"Italy"},
{name:"Teva Pharmaceutical",country:"Israel"},
{name:"Keyence",country:"Japan"},
{name:"Neste",country:"Finland"},
{name:"Shanghai International Port",country:"China"},
{name:"Nedbank",country:"South Africa"},
{name:"Bangkok Bank",country:"Thailand"},
{name:"China Reinsurance Group",country:"China"},
{name:"Formosa Plastics",country:"Taiwan"},
{name:"Telecom Italia",country:"Italy"},
{name:"Concho Resources",country:"United States"},
{name:"Covestro",country:"Germany"},
{name:"Guangzhou R&F",country:"China"},
{name:"LG",country:"South Korea"},
{name:"Liberty Global",country:"United Kingdom"},
{name:"Raymond James Financial",country:"United States"},
{name:"Fairfax Financial",country:"Canada"},
{name:"ROSSETI",country:"Russia"},
{name:"China Eastern Airlines",country:"China"},
{name:"Tata Motors",country:"India"},
{name:"AIB Group",country:"Ireland"},
{name:"Fortis (Canada)",country:"Canada"},
{name:"Woodside Petroleum",country:"Australia"},
{name:"China Steel",country:"Taiwan"},
{name:"First Republic Bank",country:"United States"},
{name:"ATOS",country:"France"},
{name:"Japan Airlines",country:"Japan"},
{name:"Garanti Bank",country:"Turkey"},
{name:"Edison International",country:"United States"},
{name:"Galp Energia",country:"Portugal"},
{name:"Infineon Technologies",country:"Germany"},
{name:"Athene Holding",country:"Bermuda"},
{name:"Old Mutual",country:"South Africa"},
{name:"AutoZone",country:"United States"},
{name:"Abu Dhabi Commercial Bank",country:"United Arab Emirates"},
{name:"Yanzhou Coal Mining",country:"China"},
{name:"Macy's",country:"United States"},
{name:"NetEase",country:"China"},
{name:"Hermès International",country:"France"},
{name:"Fanuc",country:"Japan"},
{name:"Regeneron Pharmaceuticals",country:"United States"},
{name:"Novolipetsk Steel",country:"Russia"},
{name:"Hanwha",country:"South Korea"},
{name:"Dentsu",country:"Japan"},
{name:"Carlsberg",country:"Denmark"},
{name:"Textron",country:"United States"},
{name:"Bank of Jinzhou",country:"China"},
{name:"SSE",country:"United Kingdom"},
{name:"Huatai Securities",country:"China"},
{name:"Lotte Chemical",country:"South Korea"},
{name:"Hikvision",country:"China"},
{name:"QBE Insurance Group",country:"Australia"},
{name:"Shaanxi Coal Industry",country:"China"},
{name:"Shanghai Electric Group",country:"China"},
{name:"Saudi British Bank",country:"Saudi Arabia"},
{name:"O'Reilly Automotive",country:"United States"},
{name:"ITC",country:"India"},
{name:"Chunghwa Telecom",country:"Taiwan"},
{name:"Shenzhen Overseas",country:"China"},
{name:"EnBW-Energie Baden",country:"Germany"},
{name:"Comerica",country:"United States"},
{name:"Inner Mongolia Yili",country:"China"},
{name:"Genuine Parts",country:"United States"},
{name:"PKO Bank Polski",country:"Poland"},
{name:"PG&E",country:"United States"},
{name:"Discovery",country:"United States"},
{name:"Ferguson",country:"United Kingdom"},
{name:"Huishang Bank",country:"China"},
{name:"Sanlam",country:"South Africa"},
{name:"Williams",country:"United States"},
{name:"Deutsche Wohnen",country:"Germany"},
{name:"S&P Global",country:"United States"},
{name:"Wanhua Chemical Group",country:"China"},
{name:"Fortum",country:"Finland"},
{name:"Mega Financial Holding",country:"Taiwan"},
{name:"JBS",country:"Brazil"},
{name:"China Coal Energy",country:"China"},
{name:"Emaar Properties",country:"United Arab Emirates"},
{name:"Canadian Pacific Railway",country:"Canada"},
{name:"Evraz Group",country:"United Kingdom"},
{name:"Mitsubishi Motors",country:"Japan"},
{name:"Wuliangye Yibin",country:"China"},
{name:"Intuit",country:"United States"},
{name:"LabCorp",country:"United States"},
{name:"PTT Global Chemical",country:"Thailand"},
{name:"Bank Negara Indonesia",country:"Indonesia"},
{name:"Galaxy Entertainment",country:"Hong Kong"},
{name:"Gemdale",country:"China"},
{name:"E-Trade Financial",country:"United States"},
{name:"Kuehne & Nagel International",country:"Switzerland"},
{name:"Kone",country:"Finland"},
{name:"Ryanair Holdings",country:"Ireland"},
{name:"Great Wall Motor",country:"China"},
{name:"MGM Resorts",country:"United States"},
{name:"Tokyo Gas",country:"Japan"},
{name:"YPF",country:"Argentina"},
{name:"Daiwa Securities",country:"Japan"},
{name:"ThyssenKrupp Group",country:"Germany"},
{name:"Vestas Wind Systems",country:"Denmark"},
{name:"Sabanci Holding",country:"Turkey"},
{name:"Mazda Motor",country:"Japan"},
{name:"DP World",country:"United Arab Emirates"},
{name:"Bharti Airtel",country:"India"},
{name:"Valeo",country:"France"},
{name:"Ameren",country:"United States"},
{name:"Secom",country:"Japan"},
{name:"Brighthouse Financial",country:"United States"},
{name:"Hilton",country:"United States"},
{name:"Wipro",country:"India"},
{name:"Itaúsa",country:"Brazil"},
{name:"China Huarong Asset Management",country:"China"},
{name:"Amphenol",country:"United States"},
{name:"Daiichi Sankyo",country:"Japan"},
{name:"JSW Steel",country:"India"},
{name:"Schindler Holding",country:"Switzerland"},
{name:"Power Grid of India",country:"India"},
{name:"Scentre Group",country:"Australia"},
{name:"Seagate Technology",country:"Ireland"},
{name:"OTP Bank",country:"Hungary"},
{name:"Aena",country:"Spain"},
{name:"Akbank",country:"Turkey"},
{name:"SVB Financial Group",country:"United States"},
{name:"Unum",country:"United States"},
{name:"Towngas",country:"Hong Kong"},
{name:"Kuwait Finance House",country:"Kuwait"},
{name:"Future Land Development Holdings",country:"China"},
{name:"Hindalco Industries",country:"India"},
{name:"China Resources Pharmaceutical Group",country:"Hong Kong"},
{name:"Eastman Chemical",country:"United States"},
{name:"HCL Technologies",country:"India"},
{name:"Conagra Brands",country:"United States"},
{name:"CP All",country:"Thailand"},
{name:"Stora Enso",country:"Finland"},
{name:"Bank Leumi",country:"Israel"},
{name:"Lear",country:"United States"},
{name:"Kohl's",country:"United States"},
{name:"MOL Hungarian Oil",country:"Hungary"},
{name:"Xiamen C&D",country:"China"},
{name:"S.F. Holding",country:"China"},
{name:"Zijin Mining Group",country:"China"},
{name:"CapitaLand",country:"Singapore"},
{name:"Steinhoff International",country:"Netherlands"},
{name:"Inpex",country:"Japan"},
{name:"China National Nuclear Power",country:"China"},
{name:"GF Securities",country:"China"},
{name:"Zoetis",country:"United States"},
{name:"Halkbank",country:"Turkey"},
{name:"Pembina Pipeline",country:"Canada"},
{name:"ASE Technology Holding",country:"Taiwan"},
{name:"Taisei",country:"Japan"},
{name:"TDK",country:"Japan"},
{name:"Shenwan Hongyuan Group",country:"China"},
{name:"Weyerhaeuser",country:"United States"},
{name:"Kajima",country:"Japan"},
{name:"Banque Saudi Fransi",country:"Saudi Arabia"},
{name:"Cheniere Energy",country:"United States"},
{name:"STMicroelectronics",country:"Switzerland"},
{name:"L3Harris Technologies",country:"United States"},
{name:"VakifBank",country:"Turkey"},
{name:"Randstad Holding",country:"Netherlands"},
{name:"South32",country:"Australia"},
{name:"United Rentals",country:"United States"},
{name:"Braskem",country:"Brazil"},
{name:"Mediobanca",country:"Italy"},
{name:"Arrow Electronics",country:"United States"},
{name:"Marathon Oil",country:"United States"},
{name:"Obayashi",country:"Japan"},
{name:"RiseSun Real Estate Development",country:"China"},
{name:"Hormel Foods",country:"United States"},
{name:"Alliance Data Systems",country:"United States"},
{name:"Franklin Resources",country:"United States"},
{name:"China Hongqiao Group",country:"China"},
{name:"Hershey",country:"United States"},
{name:"CMS Energy",country:"United States"},
{name:"Aluminum Corp of China",country:"China"},
{name:"Severstal",country:"Russia"},
{name:"Dubai Islamic Bank",country:"United Arab Emirates"},
{name:"BAIC Motor",country:"China"},
{name:"Julius Baer Group",country:"Switzerland"},
{name:"Roper Technologies",country:"United States"},
{name:"Swatch Group",country:"Switzerland"},
{name:"Snam",country:"Italy"},
{name:"Norsk Hydro",country:"Norway"},
{name:"AntarChile",country:"Chile"},
{name:"Suntory Beverage & Food",country:"Japan"},
{name:"Fortescue Metals Group",country:"Australia"},
{name:"MTN Group",country:"South Africa"},
{name:"TCL",country:"China"},
{name:"China Merchants Securities",country:"China"},
{name:"Quanta Computer",country:"Taiwan"},
{name:"KT",country:"South Korea"},
{name:"Shanghai Pharmaceuticals",country:"China"},
{name:"Scor",country:"France"},
{name:"Bankia",country:"Spain"},
{name:"Dollar Tree",country:"United States"},
{name:"Origin Energy",country:"Australia"},
{name:"Shengjing Bank",country:"China"},
{name:"Ball",country:"United States"},
{name:"China Gezhouba",country:"China"},
{name:"Yum! Brands",country:"United States"},
{name:"Air France-KLM",country:"France"},
{name:"Amadeus IT Group",country:"Spain"},
{name:"AGC",country:"Japan"},
{name:"Arch Capital Group",country:"Bermuda"},
{name:"CDW",country:"United States"},
{name:"Tenaris",country:"Luxembourg"},
{name:"Bank of Ireland",country:"Ireland"},
{name:"Logan Property Holdings",country:"China"},
{name:"Arconic",country:"United States"},
{name:"Bank Hapoalim",country:"Israel"},
{name:"Beiersdorf",country:"Germany"},
{name:"IQVIA",country:"United States"},
{name:"Vertex Pharmaceuticals",country:"United States"},
{name:"Alstom",country:"France"},
{name:"AvalonBay Communities",country:"United States"},
{name:"CEZ Group",country:"Czech Republic"},
{name:"Fiserv",country:"United States"},
{name:"Bâloise Group",country:"Switzerland"},
{name:"China Grand Automotive Services",country:"China"},
{name:"Mylan",country:"United Kingdom"},
{name:"Bank of East Asia",country:"Hong Kong"},
{name:"Qurate Retail Group",country:"United States"},
{name:"Krung Thai Bank",country:"Thailand"},
{name:"Mahindra & Mahindra",country:"India"},
{name:"CGI Group",country:"Canada"},
{name:"Cemex",country:"Mexico"},
{name:"Altice USA",country:"United States"},
{name:"Cosco Shipping",country:"China"},
{name:"Sharp",country:"Japan"},
{name:"WW Grainger",country:"United States"},
{name:"Leonardo",country:"Italy"},
{name:"Gap",country:"United States"},
{name:"American Financial Group",country:"United States"},
{name:"Uni-President",country:"Taiwan"},
{name:"Korea Gas",country:"South Korea"},
{name:"Cenovus Energy",country:"Canada"},
{name:"CenterPoint Energy",country:"United States"},
{name:"Motorola Solutions",country:"United States"},
{name:"SMC",country:"Japan"},
{name:"Meituan Dianping",country:"China"},
{name:"T Rowe Price",country:"United States"},
{name:"Agile Group Holdings",country:"China"},
{name:"TUI",country:"Germany"},
{name:"Expedia Group",country:"United States"},
{name:"Public Storage",country:"United States"},
{name:"Guangzhou Rural Commercial Bank",country:"China"},
{name:"Zions Bancorp",country:"United States"},
{name:"Shiseido",country:"Japan"},
{name:"C.H. Robinson",country:"United States"},
{name:"WR Berkley",country:"United States"},
{name:"Samsung SDI",country:"South Korea"},
{name:"ZTE",country:"China"},
{name:"Voya Financial",country:"United States"},
{name:"Arab National Bank",country:"Saudi Arabia"},
{name:"Centrica",country:"United Kingdom"},
{name:"Financiere de l'Odet",country:"France"},
{name:"Wens Foodstuff Group",country:"China"},
{name:"Electronic Arts",country:"United States"},
{name:"Bank Of Hangzhou",country:"China"},
{name:"GS Holdings",country:"South Korea"},
{name:"Pgnig Group",country:"Poland"},
{name:"HollyFrontier",country:"United States"},
{name:"DSV",country:"Denmark"},
{name:"Intuitive Surgical",country:"United States"},
{name:"Legrand",country:"France"},
{name:"Inner Mongolia Baotou Steel",country:"China"},
{name:"En+ Group Plc Sponsored GDR RegS",country:"United Kingdom"},
{name:"Sany Heavy Industry",country:"China"},
{name:"BDO Unibank",country:"Philippines"},
{name:"China Gas Holdings",country:"Hong Kong"},
{name:"Aeroports de Paris",country:"France"},
{name:"Diamondback Energy",country:"United States"},
{name:"Asr Nederland",country:"Netherlands"},
{name:"NEC",country:"Japan"},
{name:"Db Insurance",country:"South Korea"},
{name:"JM Smucker",country:"United States"},
{name:"Schaeffler",country:"Germany"},
{name:"Zimmer Biomet",country:"United States"},
{name:"China Jinmao",country:"Hong Kong"},
{name:"Hengli Petrochemical",country:"China"},
{name:"ALFA",country:"Mexico"},
{name:"Shanghai Construction",country:"China"},
{name:"Qatar Islamic Bank",country:"Qatar"},
{name:"CJ Cheiljedang",country:"South Korea"},
{name:"Turkish Airlines",country:"Turkey"},
{name:"Thomson Reuters",country:"Canada"},
{name:"Investor AB",country:"Sweden"},
{name:"Adecco",country:"Switzerland"},
{name:"Rockwell Automation",country:"United States"},
{name:"Moody's",country:"United States"},
{name:"Datang International Power",country:"China"},
{name:"Accor",country:"France"},
{name:"IndusInd Bank",country:"India"},
{name:"Intact Financial",country:"Canada"},
{name:"J Sainsbury",country:"United Kingdom"},
{name:"Thai Beverage",country:"Thailand"},
{name:"Yamaha Motor",country:"Japan"},
{name:"Cintas",country:"United States"},
{name:"Beijing Enterprises",country:"Hong Kong"},
{name:"Gallagher",country:"United States"},
{name:"Continental Resources",country:"United States"},
{name:"Daito Trust Construction",country:"Japan"},
{name:"China Shipbuilding Industry",country:"China"},
{name:"Shin Kong Financial",country:"Taiwan"},
{name:"BBMG",country:"China"},
{name:"MediaTek",country:"Taiwan"},
{name:"Onex",country:"Canada"},
{name:"Tokyu",country:"Japan"},
{name:"WellCare Health Plans",country:"United States"},
{name:"Mitsubishi UFJ Lease",country:"Japan"},
{name:"Celanese",country:"United States"},
{name:"Hesteel",country:"China"},
{name:"Interactive Brokers Group",country:"United States"},
{name:"Sumitomo Metal Mining",country:"Japan"},
{name:"Japan Exchange Group",country:"Japan"},
{name:"Mohawk Industries",country:"United States"},
{name:"Sojitz",country:"Japan"},
{name:"Investec",country:"United Kingdom"},
{name:"NetApp",country:"United States"},
{name:"Yum China Holdings",country:"China"},
{name:"Melrose Industries Plc",country:"United Kingdom"},
{name:"Universal Health",country:"United States"},
{name:"Gecina",country:"France"},
{name:"Restaurant Brands International",country:"Canada"},
{name:"Dexia",country:"Belgium"},
{name:"Norwegian Cruise Line Holdings",country:"United States"},
{name:"Sika",country:"Switzerland"},
{name:"Zhejiang Zheneng Electric Power",country:"China"},
{name:"Singapore Airlines",country:"Singapore"},
{name:"Technipfmc",country:"United Kingdom"},
{name:"BCI-Banco Credito",country:"Chile"},
{name:"SDIC Power Holdings",country:"China"},
{name:"Dassault Aviation",country:"France"},
{name:"First Financial Holding",country:"Taiwan"},
{name:"Barrick Gold",country:"Canada"},
{name:"Shimizu",country:"Japan"},
{name:"Vistra Energy",country:"United States"},
{name:"Invesco",country:"United States"},
{name:"Mosaic",country:"United States"},
{name:"Oi",country:"Brazil"},
{name:"Jiangsu Yanghe Brewery",country:"China"},
{name:"Klepierre",country:"France"},
{name:"SM Investments",country:"Philippines"},
{name:"Harris",country:"United States"},
{name:"Agilent Technologies",country:"United States"},
{name:"Altice Europe",country:"Netherlands"},
{name:"Joint Stock Commercial Bank for Foreign Trade of Vietnam",country:"Vietnam"},
{name:"Kyushu Electric Power",country:"Japan"},
{name:"Markel",country:"United States"},
{name:"Welltower",country:"United States"},
{name:"Twitter",country:"United States"},
{name:"Kerry Group",country:"Ireland"},
{name:"Angang Steel",country:"China"},
{name:"Hoya",country:"Japan"},
{name:"Illumina",country:"United States"},
{name:"Mondi",country:"United Kingdom"},
{name:"Steel Dynamics",country:"United States"},
{name:"Bajaj Finserv",country:"India"},
{name:"Boston Properties",country:"United States"},
{name:"Insurance Australia Group",country:"Australia"},
{name:"American Water Works",country:"United States"},
{name:"Goodyear",country:"United States"},
{name:"Banco de Sabadell",country:"Spain"},
{name:"Knorr-Bremse",country:"Germany"},
{name:"Annaly Capital Management",country:"United States"},
{name:"Helvetia Holding",country:"Switzerland"},
{name:"LG Display",country:"South Korea"},
{name:"Harbin Bank",country:"China"},
{name:"Alinma Bank",country:"Saudi Arabia"},
{name:"Grupo Inbursa",country:"Mexico"},
{name:"AGL Energy",country:"Australia"},
{name:"E.Sun Financial",country:"Taiwan"},
{name:"Paychex",country:"United States"},
{name:"AerCap Holdings",country:"Ireland"},
{name:"Rongsheng Petrochemical",country:"China"},
{name:"Bunge",country:"United States"},
{name:"Meiji Holdings",country:"Japan"},
{name:"Bankinter",country:"Spain"},
{name:"Westlake Chemical",country:"United States"},
{name:"Grifols",country:"Spain"},
{name:"KLA-Tencor",country:"United States"},
{name:"Monster Beverage",country:"United States"},
{name:"Darden Restaurants",country:"United States"},
{name:"Ferrovial",country:"Spain"},
{name:"Encana",country:"Canada"},
{name:"Taiwan Cooperative Financial",country:"Taiwan"},
{name:"Industries Qatar",country:"Qatar"},
{name:"Clorox",country:"United States"},
{name:"Lonza Group",country:"Switzerland"},
{name:"Hankyu Hanshin Holdings",country:"Japan"},
{name:"Ternium",country:"Luxembourg"},
{name:"Tohoku Electric Power",country:"Japan"},
{name:"BorgWarner",country:"United States"},
{name:"Attijariwafa Bank",country:"Morocco"},
{name:"Ulta Beauty",country:"United States"},
{name:"CIFI Holdings Group",country:"China"},
{name:"Samsung SDS",country:"South Korea"},
{name:"Molina Healthcare",country:"United States"},
{name:"Saudi Arabian Mining",country:"Saudi Arabia"},
{name:"Interpublic Group",country:"United States"},
{name:"Skanska",country:"Sweden"},
{name:"Amcor",country:"Australia"},
{name:"Guosen Securities",country:"China"},
{name:"SGS",country:"Switzerland"},
{name:"Tokyo Century",country:"Japan"},
{name:"Evergy",country:"United States"},
{name:"PVH",country:"United States"},
{name:"Host Hotels & Resorts",country:"United States"},
{name:"Saputo",country:"Canada"},
{name:"Whirlpool",country:"United States"},
{name:"TransDigm Group",country:"United States"},
{name:"Kobe Steel",country:"Japan"},
{name:"Voestalpine",country:"Austria"},
{name:"Aramark",country:"United States"},
{name:"China Galaxy Securities",country:"China"},
{name:"China International Marine",country:"China"},
{name:"CJ Corporation",country:"South Korea"},
{name:"Jeronimo Martins",country:"Portugal"},
{name:"Terna",country:"Italy"},
{name:"PulteGroup",country:"United States"},
{name:"China Development Financial",country:"Taiwan"},
{name:"China Resources Power",country:"Hong Kong"},
{name:"Bank Pekao",country:"Poland"},
{name:"Covivio",country:"France"},
{name:"Oriental Land",country:"Japan"},
{name:"Xilinx",country:"United States"},
{name:"Schroders",country:"United States"},
{name:"Wynn Resorts",country:"United States"},
{name:"Bank of Tianjin",country:"China"},
{name:"GD Power Development",country:"China"},
{name:"Equinix",country:"United States"},
{name:"UBI Banca",country:"Italy"},
{name:"Cosmo Energy Holdings",country:"Japan"},
{name:"UCB",country:"Belgium"},
{name:"3i Group",country:"United Kingdom"},
{name:"Yara International",country:"Norway"},
{name:"GAIL India",country:"India"},
{name:"Givaudan",country:"Switzerland"},
{name:"Hyundai Steel",country:"South Korea"},
{name:"Inter Rao",country:"Russia"},
{name:"Ferrari",country:"Italy"},
{name:"Industrial Alliance Insurance",country:"Canada"},
{name:"Vienna Insurance Group",country:"Austria"},
{name:"Petronas Chemicals",country:"Malaysia"},
{name:"Terumo",country:"Japan"},
{name:"Newmont Mining",country:"United States"},
{name:"Masco",country:"United States"},
{name:"Ricoh",country:"Japan"},
{name:"Top Frontier Investment Holdings",country:"Philippines"},
{name:"Punjab National Bank",country:"India"},
{name:"Edwards Lifesciences",country:"United States"},
{name:"Pegatron",country:"Taiwan"},
{name:"Indorama Ventures",country:"Thailand"},
{name:"Bank Of Guiyang",country:"China"},
{name:"S-Oil",country:"South Korea"},
{name:"Arkema",country:"France"},
{name:"Airports of Thailand",country:"Thailand"},
{name:"NRG Energy",country:"United States"},
{name:"Dassault Systemes",country:"France"},
{name:"Experian",country:"Ireland"},
{name:"US Steel",country:"United States"},
{name:"Advanced Info Service",country:"Thailand"},
{name:"Expeditors International",country:"United States"},
{name:"Jiangsu Hengrui Medicine",country:"China"},
{name:"Hess",country:"United States"},
{name:"HAL Trust",country:"Monaco"},
{name:"LG Household & Health Care",country:"South Korea"},
{name:"Grasim Industries",country:"India"},
{name:"Phoenix Group Holdings",country:"United Kingdom"},
{name:"Assa Abloy",country:"Sweden"},
{name:"Charoen Pokphand Foods",country:"Thailand"},
{name:"Worldpay",country:"United States"},
{name:"Yuanta Financial Holding",country:"Taiwan"},
{name:"Concordia Financial Group",country:"Japan"},
{name:"SKF Group",country:"Sweden"},
{name:"Genworth Financial",country:"United States"},
{name:"Bank of Baroda",country:"India"},
{name:"Jiangxi Copper",country:"China"},
{name:"Bank of Changsha",country:"China"},
{name:"China Mengniu Dairy",country:"Hong Kong"},
{name:"Grupo Elektra",country:"Mexico"},
{name:"HCP",country:"United States"},
{name:"Equity Residential",country:"United States"},
{name:"Shionogi",country:"Japan"},
{name:"Foshan Haitian Flavouring and Food",country:"China"},
{name:"Quest Diagnostics",country:"United States"},
{name:"Ayala",country:"Philippines"},
{name:"China International Capital",country:"China"},
{name:"Magnitogorsk Iron & Steel",country:"Russia"},
{name:"Ashtead Group",country:"United Kingdom"},
{name:"Bank Of Chengdu",country:"China"},
{name:"Brown-Forman",country:"United States"},
{name:"Hunan Valin Steel",country:"China"},
{name:"Delta Electronics",country:"Taiwan"},
{name:"East West Bancorp",country:"United States"},
{name:"New Residential Investment",country:"United States"},
{name:"Fastenal",country:"United States"},
{name:"Power Finance",country:"India"},
{name:"Henry Schein",country:"United States"},
{name:"FleetCor Technologies",country:"United States"},
{name:"Hexagon",country:"Sweden"},
{name:"Dai Nippon Printing",country:"Japan"},
{name:"Metro Group",country:"Germany"},
{name:"Goodman Group",country:"Australia"},
{name:"Torchmark",country:"United States"},
{name:"Ctrip.com International",country:"China"},
{name:"China Life Insurance (Taiwan)",country:"Taiwan"},
{name:"McCormick",country:"United States"},
{name:"Storebrand",country:"Norway"},
{name:"HNA Technology",country:"China"},
{name:"Apache",country:"United States"},
{name:"Brenntag",country:"Germany"},
{name:"RSA Insurance Group",country:"United Kingdom"},
{name:"NVR",country:"United States"},
{name:"Skyworks Solutions",country:"United States"},
{name:"China International Travel Service",country:"China"},
{name:"Johnson Matthey",country:"United Kingdom"},
{name:"Hua Nan Financial",country:"Taiwan"},
{name:"Huntington Ingalls Industries",country:"United States"},
{name:"Unicharm",country:"Japan"},
{name:"China Molybdenum",country:"China"},
{name:"Yango Group",country:"China"},
{name:"Wolters Kluwer",country:"Netherlands"},
{name:"Hyundai Marine & Fire",country:"South Korea"},
{name:"Umicore",country:"Belgium"},
{name:"Waste Connections",country:"Canada"},
{name:"Sino-Ocean Group Holding",country:"China"},
{name:"AGNC Investment",country:"United States"},
{name:"Signature Bank",country:"United States"},
{name:"Cerner",country:"United States"},
{name:"Huadian Power International",country:"China"},
{name:"Power Assets Holdings",country:"Hong Kong"},
{name:"Ahli United Bank",country:"Bahrain"},
{name:"Qantas Airways",country:"Australia"},
{name:"Ametek",country:"United States"},
{name:"Cathay Pacific Airways",country:"Hong Kong"},
{name:"LKQ",country:"United States"},
{name:"LARGAN Precision",country:"Taiwan"},
{name:"X5 Retail Group",country:"Netherlands"},
{name:"Canara Bank",country:"India"},
{name:"Digital Realty Trust",country:"United States"},
{name:"Crown Holdings",country:"United States"},
{name:"Doosan",country:"South Korea"},
{name:"Valeant Pharmaceuticals",country:"Canada"},
{name:"Transurban Group",country:"Australia"},
{name:"Mitsui Chemicals",country:"Japan"},
{name:"Maanshan Iron & Steel",country:"China"},
{name:"Jacobs Engineering",country:"United States"},
{name:"Partners Group Holding",country:"Switzerland"},
{name:"AVIC Capita",country:"China"},
{name:"Focus Media Information Technology",country:"China"},
{name:"Koito Manufacturing",country:"Japan"},
{name:"Check Point Software",country:"Israel"},
{name:"Quinenco",country:"Chile"},
{name:"Leidos",country:"United States"},
{name:"Dover",country:"United States"},
{name:"Grupo Bimbo",country:"Mexico"},
{name:"Sino Biopharmaceutical",country:"Hong Kong"},
{name:"Everest Re Group",country:"Bermuda"},
{name:"Jinke Property Group",country:"China"},
{name:"Bombardier",country:"Canada"},
{name:"L Brands",country:"United States"},
{name:"Wuestenrot & Wuerttembergische",country:"Germany"},
{name:"DaVita",country:"United States"},
{name:"Ventas",country:"United States"},
{name:"Coca-Cola HBC",country:"Switzerland"},
{name:"Tenet Healthcare",country:"United States"},
{name:"Metro",country:"Canada"},
{name:"Bluescope Steel",country:"Australia"},
{name:"Hyundai Heavy Industries",country:"South Korea"},
{name:"Techtronic Industries",country:"Hong Kong"},
{name:"Fukuoka Financial Group",country:"Japan"},
{name:"Tractor Supply",country:"United States"},
{name:"National Oilwell Varco",country:"United States"},
{name:"Shanxi Taigang Stainless",country:"China"},
{name:"Shinsei Bank",country:"Japan"},
{name:"Lotte Shopping",country:"South Korea"},
{name:"Alrosa",country:"Russia"},
{name:"Fidelity National Financial",country:"United States"},
{name:"RTL Group",country:"Luxembourg"},
{name:"Manpower",country:"United States"},
{name:"Navient",country:"United States"},
{name:"Banco BPM",country:"Italy"},
{name:"Chow Tai Fook Jewellery",country:"Hong Kong"},
{name:"Bank of India",country:"India"},
{name:"Liberty Expedia Holdings",country:"United States"},
{name:"Shenzhou International Group Holdings",country:"Hong Kong"},
{name:"Bunzl",country:"United Kingdom"},
{name:"US Foods",country:"United States"},
{name:"Chugoku Electric Power",country:"Japan"},
{name:"Contemporary Amperex Technology",country:"China"},
{name:"Emera",country:"Canada"},
{name:"KION Group",country:"Germany"},
{name:"Daishi Hokuetsu Financial Group",country:"Japan"},
{name:"RHB Bank",country:"Malaysia"},
{name:"Nordstrom",country:"United States"},
{name:"Yamato Holdings",country:"Japan"},
{name:"Chesapeake Energy",country:"United States"},
{name:"NARI Technology Development",country:"China"},
{name:"Santos",country:"Australia"},
{name:"Eisai",country:"Japan"},
{name:"Electric Power Development",country:"Japan"},
{name:"Targa Resources",country:"United States"},
{name:"Keppel",country:"Singapore"},
{name:"Advance Auto Parts",country:"United States"},
{name:"Bank of Chongqing",country:"China"},
{name:"Popular",country:"United States"},
{name:"Zhongsheng Group Holdings",country:"China"},
{name:"IHS Markit",country:"United Kingdom"},
{name:"Campbell Soup",country:"United States"},
{name:"Microchip Technology",country:"United States"},
{name:"Coloplast",country:"Denmark"},
{name:"STRABAG",country:"Austria"},
{name:"Chiba Bank",country:"Japan"},
{name:"Colruyt",country:"Belgium"},
{name:"Brambles",country:"Australia"},
{name:"Hydro One",country:"Canada"},
{name:"Verisk Analytics",country:"United States"},
{name:"Oji Holdings",country:"Japan"},
{name:"Greentown China Holdings",country:"China"},
{name:"Magnit",country:"Russia"},
{name:"Osaka Gas",country:"Japan"},
{name:"Segro",country:"United Kingdom"},
{name:"Alleghany",country:"United States"},
{name:"Olam International",country:"Singapore"},
{name:"Bohai Leasing",country:"China"},
{name:"Jones Lang LaSalle",country:"United States"},
{name:"Smith & Nephew",country:"United Kingdom"},
{name:"J.B. Hunt Transport Services",country:"United States"},
{name:"Medipal Holdings",country:"Japan"},
{name:"360 Security Technology",country:"China"},
{name:"Coty",country:"United States"},
{name:"VeriSign",country:"United States"},
{name:"St. James's Place",country:"United Kingdom"},
{name:"Barratt Developments",country:"United Kingdom"},
{name:"BPER Banca",country:"Italy"},
{name:"Maxim Integrated Products",country:"United States"},
{name:"Meritz Financial Group",country:"South Korea"},
{name:"Red Eléctrica",country:"Spain"},
{name:"NEXON",country:"Japan"},
{name:"Packaging Corp of America",country:"United States"},
{name:"Shanghai International Airport",country:"China"},
{name:"Materials Industry Zhongda Group",country:"China"},
{name:"Hainan Airlines",country:"China"},
{name:"Cincinnati Financial",country:"United States"},
{name:"Garmin",country:"Switzerland"},
{name:"Canadian Tire",country:"Canada"},
{name:"Nine Dragons Paper Holdings",country:"Hong Kong"},
{name:"Nippon Yusen",country:"Japan"},
{name:"Kintetsu",country:"Japan"},
{name:"Verbund",country:"Austria"},
{name:"Anta Sports Products",country:"China"},
{name:"IAC/InterActiveCorp",country:"United States"},
{name:"Global Payments",country:"United States"},
{name:"Penske Automotive",country:"United States"},
{name:"Showa Denko",country:"Japan"},
{name:"Shizuoka Bank",country:"Japan"},
{name:"Persimmon",country:"United Kingdom"},
{name:"Alfresa Holdings",country:"Japan"},
{name:"Live Nation Entertainment",country:"United States"},
{name:"XPO Logistics",country:"United States"},
{name:"Lixil Group",country:"Japan"},
{name:"Bank of Zhengzhou",country:"China"},
{name:"OMRON",country:"Japan"},
{name:"DCC",country:"Ireland"},
{name:"Sun Art Retail Group",country:"Hong Kong"},
{name:"Beijing Capital Development",country:"China"},
{name:"Advanced Micro Devices",country:"United States"},
{name:"Nitori Holdings",country:"Japan"},
{name:"Arca Continental",country:"Mexico"},
{name:"Masraf Al Rayan",country:"Qatar"},
{name:"BNK Financial Group",country:"South Korea"},
{name:"Assurant",country:"United States"},
{name:"NASDAQ",country:"United States"},
{name:"Bawag Group",country:"Austria"},
{name:"Shanghai Commercial & Savings Bank",country:"Taiwan"},
{name:"Iida Group Holdings",country:"Japan"},
{name:"Mirae Asset Daewoo",country:"South Korea"},
{name:"Far East Horizon",country:"Hong Kong"},
{name:"CSN",country:"Brazil"},
{name:"Bank Of Gansu",country:"China"},
{name:"People's United Financial",country:"United States"},
{name:"E-mart",country:"South Korea"},
{name:"Kerry Properties",country:"Hong Kong"},
{name:"ENN Energy Holdings",country:"China"},
{name:"Next",country:"United Kingdom"},
{name:"Tech Data",country:"United States"},
{name:"Wm Morrison Supermarkets",country:"United Kingdom"},
{name:"Hong Leong Financial",country:"Malaysia"},
{name:"Arab Bank",country:"Jordan"},
{name:"Sekisui Chemical",country:"Japan"},
{name:"Korea Investment Holdings",country:"South Korea"},
{name:"Flex",country:"Singapore"},
{name:"Naver",country:"South Korea"},
{name:"Orient Securities",country:"China"},
{name:"Union Bank of India",country:"India"},
{name:"Korean Air",country:"South Korea"},
{name:"Mebuki Financial Group",country:"Japan"},
{name:"Gudang Garam",country:"Indonesia"},
{name:"American Equity Investment",country:"United States"},
{name:"Spirit AeroSystems",country:"United States"},
{name:"Ooredoo Q.P.S.C",country:"Qatar"},
{name:"Yonghui Superstores",country:"China"},
{name:"Chongqing Rural Bank",country:"China"},
{name:"First Horizon National",country:"United States"},
{name:"Electrolux Group",country:"Sweden"},
{name:"Synopsys",country:"United States"},
{name:"Mitsubishi Materials",country:"Japan"},
{name:"Church & Dwight",country:"United States"},
{name:"Xylem",country:"United States"},
{name:"Total System Services",country:"United States"},
{name:"China Merchants Port Holdings",country:"Hong Kong"},
{name:"Tapestry",country:"United States"},
{name:"Compal Electronics",country:"Taiwan"},
{name:"Red Hat",country:"United States"},
{name:"Proximus",country:"Belgium"},
{name:"Waters",country:"United States"},
{name:"Sistema",country:"Russia"},
{name:"Mashreq Bank",country:"United Arab Emirates"},
{name:"Pinnacle West",country:"United States"},
{name:"Vornado Realty",country:"United States"},
{name:"Xiamen International Trade Group",country:"China"},
{name:"Reliance Steel",country:"United States"},
{name:"Abu Dhabi Islamic Bank",country:"United Arab Emirates"},
{name:"AECOM Technology",country:"United States"},
{name:"Bank Audi",country:"Lebanon"},
{name:"Kawasaki Heavy Industries",country:"Japan"},
{name:"Toppan Printing",country:"Japan"},
{name:"Boliden",country:"Sweden"},
{name:"Cielo",country:"Brazil"},
{name:"Lululemon Athletica",country:"Canada"},
{name:"Empresas CMPC",country:"Chile"},
{name:"Nitto Denko",country:"Japan"},
{name:"Huntsman",country:"United States"},
{name:"Antofagasta",country:"United Kingdom"},
{name:"Beijing Shougang",country:"China"},
{name:"B3",country:"Brazil"},
{name:"Realty Income",country:"United States"},
{name:"Bandai Namco Holdings",country:"Japan"},
{name:"Xinyu Iron & Steel",country:"China"},
{name:"Alliant Energy",country:"United States"},
{name:"Sinotruk Hong Kong",country:"China"},
{name:"Geberit",country:"Switzerland"},
{name:"KT&G",country:"South Korea"},
{name:"Spotify Technology",country:"Luxembourg"},
{name:"Yandex NV",country:"Netherlands"},
{name:"Alexion Pharmaceuticals",country:"United States"},
{name:"Micro Focus International",country:"United Kingdom"},
{name:"Mitsui OSK Lines",country:"Japan"},
{name:"Cattolica Assicurazioni",country:"Italy"},
{name:"Hyundai Engineering",country:"South Korea"},
{name:"Chang Hwa Bank",country:"Taiwan"},
{name:"China Communications Services",country:"China"},
{name:"Bajaj Auto",country:"India"},
{name:"Kingfisher",country:"United Kingdom"},
{name:"CIT Group",country:"United States"},
{name:"Nippon Express",country:"Japan"},
{name:"Dexus",country:"Australia"},
{name:"El Puerto de Liverpool",country:"Mexico"},
{name:"Israel Discount Bank",country:"Israel"},
{name:"Maroc Telecom",country:"Morocco"},
{name:"MSCI",country:"United States"},
{name:"Mettler-Toledo International",country:"United States"},
{name:"Taishin Financial Holdings",country:"Taiwan"},
{name:"Xerox",country:"United States"},
{name:"Western Union",country:"United States"},
{name:"Hang Lung Group",country:"Hong Kong"},
{name:"SEB SA",country:"France"},
{name:"Cencosud",country:"Chile"},
{name:"ICA Gruppen",country:"Sweden"},
{name:"Jyske Bank",country:"Denmark"},
{name:"KPN",country:"Netherlands"},
{name:"Ceconomy",country:"Germany"},
{name:"Halyk Bank",country:"Kazakhstan"},
{name:"Kaisa Group Holdings",country:"China"},
{name:"Jiangxi Bank",country:"China"},
{name:"Finatis",country:"France"},
{name:"Zhongyuan Bank",country:"China"},
{name:"Banca MPS",country:"Italy"},
{name:"Lindt & Sprungli",country:"Switzerland"},
{name:"Dangote Cement",country:"Nigeria"},
{name:"Epiroc",country:"Sweden"},
{name:"Jefferies Financial",country:"United States"},
{name:"Caesars Entertainment",country:"United States"},
{name:"Chemours",country:"United States"},
{name:"Blom Bank",country:"Lebanon"},
{name:"Daelim Industrial",country:"South Korea"},
{name:"HELLA",country:"Germany"},
{name:"Haseko",country:"Japan"},
{name:"ON Semiconductor Corp.",country:"United States"},
{name:"AMP",country:"Australia"},
{name:"Jabil Circuit",country:"United States"},
{name:"Noble Energy",country:"United States"},
{name:"Tech Mahindra",country:"India"},
{name:"World Fuel Services",country:"United States"},
{name:"AutoNation",country:"United States"},
{name:"CPFL Energia",country:"Brazil"},
{name:"KWG Group Holdings",country:"Hong Kong"},
{name:"GS Engineering",country:"South Korea"},
{name:"Pearson",country:"Japan"},
{name:"Starwood Property Trust",country:"United States"},
{name:"General Insurance Corporation Of India",country:"India"},
{name:"Hokuhoku Financial Group",country:"Japan"},
{name:"Taylor Wimpey",country:"United Kingdom"},
{name:"Community Health Systems",country:"United States"},
{name:"SG Holdings",country:"Japan"},
{name:"Vulcan Materials",country:"United States"},
{name:"Samsung Electro-Mechanics",country:"South Korea"},
{name:"Guangzhou Baiyunshan Pharmaceutical Holdings",country:"China"},
{name:"News Corp",country:"United States"},
{name:"Tahoe Group",country:"China"},
{name:"Qingdao Rural Commercial Bank",country:"China"},
{name:"SBI Holdings",country:"Japan"},
{name:"Almarai",country:"Saudi Arabia"},
{name:"Frontier Communications",country:"United States"},
{name:"New York Community Bancorp",country:"United States"},
{name:"Xiamen Xiangyu",country:"China"},
{name:"UGI",country:"United States"},
{name:"Mowi ASA",country:"Norway"},
{name:"MTU Aero Engines AG",country:"Germany"},
{name:"NiSource",country:"United States"},
{name:"LEG Immobilien AG",country:"Germany"},
{name:"Hopson Development Holdings",country:"Hong Kong"},
{name:"ServiceNow",country:"United States"},
{name:"IHI",country:"Japan"},
{name:"Workday",country:"United States"},
{name:"Alcoa",country:"United States"},
{name:"Old Dominion Freight Line",country:"United States"},
{name:"Air Canada",country:"Canada"},
{name:"Wistron",country:"Taiwan"},
{name:"Citrix Systems",country:"United States"},
{name:"Tiffany & Co.",country:"United States"},
{name:"EMS-Chemie Holding",country:"Switzerland"},
{name:"Banco Comercial Portugues",country:"Portugal"},
{name:"Avery Dennison",country:"United States"},
{name:"Hertz Global Holdings",country:"United States"},
{name:"First Quantum Minerals",country:"Canada"},
{name:"Symantec",country:"United States"},
{name:"Times Property Holdings",country:"China"},
{name:"Nishi-nippon Financial Holdings",country:"Japan"},
{name:"Kyushu Financial Group",country:"Japan"},
{name:"China Resources Gas Group",country:"Hong Kong"},
{name:"Pan Pacific International Holdings",country:"Japan"},
{name:"Yamaguchi Financial",country:"Japan"},
{name:"NSK",country:"Japan"},
{name:"Hachijuni Bank",country:"Japan"},
{name:"Ajinomoto",country:"Japan"},
{name:"Olympus",country:"Japan"},
{name:"Kansas City Southern",country:"United States"},
{name:"Gjensidige Forsikring",country:"Norway"},
{name:"Renesas Electronics",country:"Japan"},
{name:"Caltex Australia",country:"Australia"},
{name:"Luzhou Lao Jiao",country:"China"},
{name:"Match Group",country:"United States"},
{name:"SS&C Technologies",country:"United States"},
{name:"Autodesk",country:"United States"},
{name:"Sun Pharma Industries",country:"India"},
{name:"North Pacific Bank",country:"Japan"},
{name:"Uniqa",country:"Austria"},
{name:"Pirelli",country:"Italy"},
{name:"Alexandria Real Estate Equities",country:"United States"},
{name:"Banco Davivienda",country:"Colombia"},
{name:"Csc Financial",country:"China"},
{name:"PBF Energy",country:"United States"},
{name:"Luxshare Precision Industry",country:"China"},
{name:"Minebea",country:"Japan"},
{name:"Rajesh Exports",country:"India"},
{name:"Bank of Kyoto",country:"Japan"},
{name:"Align Technology",country:"United States"},
{name:"PGE Polska Grupa Energetyczna",country:"Poland"},
{name:"Hiroshima Bank",country:"Japan"},
{name:"Zhejiang Longsheng Group",country:"China"},
{name:"Fastighets Balder",country:"Sweden"},
{name:"INTL FCStone",country:"United States"},
{name:"Latam Airlines",country:"Chile"},
{name:"BOK Financial",country:"United States"},
{name:"Quilter",country:"United Kingdom"},
{name:"Essex Property Trust",country:"United States"},
{name:"Cullen/Frost Bankers",country:"United States"},
{name:"Guangdong Investment",country:"Hong Kong"},
{name:"China Resources Cement Holdings",country:"Hong Kong"},
{name:"Shimano",country:"Japan"},
{name:"Ares Capital",country:"United States"},
{name:"77 Bank",country:"Japan"},
{name:"Kangmei Pharmaceutical",country:"China"},
{name:"Banque Cantonale Vaudoise",country:"Switzerland"},
{name:"Chugoku Bank",country:"Japan"},
{name:"Tosoh",country:"Japan"},
{name:"Ultrapar Participacoes",country:"Brazil"},
{name:"LG Uplus",country:"South Korea"},
{name:"Metropolitan Bank & Trust",country:"Philippines"},
{name:"Newell Brands",country:"United States"},
{name:"Chongqing Changan Auto",country:"China"},
{name:"Petro Rabigh",country:"Saudi Arabia"},
{name:"Tingyi Holding",country:"China"},
{name:"SLM",country:"United States"},
{name:"National Bank of Greece",country:"Greece"},
{name:"Merlin Properties SOCIMI S.A",country:"Spain"},
{name:"SYNNEX",country:"United States"},
{name:"Copart",country:"United States"},
{name:"Gunma Bank",country:"Japan"},
{name:"Bank Muscat",country:"Oman"},
{name:"Toll Brothers",country:"United States"},
{name:"Acciona",country:"Spain"},
{name:"GPT Group",country:"Australia"},
{name:"Shenzhen Mindray Bio-Medical Electronics",country:"China"},
{name:"Mr. Cooper Group",country:"United States"},
{name:"Burlington Stores,",country:"United States"},
{name:"Piraeus Bank",country:"Greece"},
{name:"Yunnan Baiyao Group",country:"China"},
{name:"Companhia Brasileira de Distribuicao",country:"Brazil"},
{name:"Erdemir",country:"Turkey"},
{name:"Avis Budget Group",country:"United States"},
{name:"Frasers Property Limited",country:"Singapore"},
{name:"Whitbread",country:"United Kingdom"},
{name:"Invitation Homes",country:"United States"},
{name:"Alpha Bank",country:"Greece"},
{name:"Hyundai Glovis",country:"South Korea"},
{name:"Novozymes",country:"Denmark"},
{name:"Mizrahi Tefahot Bank",country:"Israel"},
{name:"Wärtsilä",country:"Finland"},
{name:"Foot Locker",country:"United States"},
{name:"Alaska Air Group",country:"United States"},
{name:"Square",country:"United States"},
{name:"Iyo Bank",country:"Japan"},
{name:"Nippon Steel Trading",country:"Japan"},
{name:"China Longyuan Power",country:"China"},
{name:"Eurobank Ergasias",country:"Greece"},
{name:"Ralph Lauren",country:"United States"},
{name:"Deutsche Pfandbriefbank",country:"Germany"},
{name:"Safaricom",country:"Kenya"},
{name:"New Hope Liuhe",country:"China"},
{name:"Unicaja Banco",country:"Spain"},
{name:"Rite Aid",country:"United States"},
{name:"Far Eastern New Century",country:"Taiwan"},
{name:"Industrivarden",country:"Sweden"},
{name:"W.P. Carey",country:"United States"},
{name:"Steel Authority of India",country:"India"},
{name:"Everbright Securities",country:"China"},
{name:"Wayfair",country:"United States"},
{name:"Jiangsu Zhongnan Construction Group",country:"China"},
{name:"Mercuries & Associates",country:"Taiwan"},
{name:"Snap-on",country:"United States"},
{name:"Liuzhou Iron & Steel",country:"China"},
{name:"Suzuken",country:"Japan"},
{name:"China Aviation Oil",country:"Singapore"},
{name:"China National Chemical",country:"China"},
{name:"Nielsen",country:"United States"},
{name:"Sterling Bancorp",country:"United States"},
{name:"Pinduoduo",country:"China"},
{name:"DGB Financial Group",country:"South Korea"},
{name:"Commercial Bank of Qatar",country:"Qatar"},
{name:"Avnet",country:"United States"},
{name:"Viva Energy Group",country:"Australia"},
{name:"Kingboard Holdings",country:"Hong Kong"},
{name:"Moscow Exchange",country:"Russia"},
{name:"Adani Ports & Special Economic Zone",country:"India"},
{name:"Great Eagle Holdings",country:"Hong Kong"},
{name:"Cabot Oil & Gas",country:"United States"},
{name:"BayWa",country:"Germany"},
{name:"Juroku Bank",country:"Japan"},
{name:"Synovus Financial",country:"United States"},
{name:"Hyakugo Bank",country:"Japan"},
{name:"Fluor",country:"United States"},
{name:"Cybg",country:"United Kingdom"},
{name:"FinecoBank",country:"Italy"},
{name:"Commercial Bank For Investment & Development Of Vietnam",country:"Vietnam"},
{name:"Empire",country:"Canada"},
{name:"Hakuhodo DY Holdings",country:"Japan"},
{name:"Rexel",country:"France"},
{name:"JG Summit Holdings",country:"Philippines"},
{name:"Inner Mongolia Yitai Coal",country:"China"},
{name:"Hengan International Group",country:"China"},
{name:"ResMed",country:"United States"},
{name:"Wendel",country:"France"},
{name:"Fuyao Glass Industry Group",country:"China"},
{name:"Seiko Epson",country:"Japan"},
{name:"Shiga Bank",country:"Japan"},
{name:"Banco de Chile",country:"Chile"},
{name:"Banca Mediolanum",country:"Italy"},
{name:"Hanwa",country:"Japan"},
{name:"Atmos Energy",country:"United States"},
{name:"IDBI Bank",country:"India"},
{name:"Arista Networks",country:"United States"},
{name:"Burelle",country:"France"},
{name:"Martin Marietta Materials",country:"United States"},
{name:"Metalurgica Gerdau",country:"Brazil"},
{name:"Atlassian",country:"United Kingdom"},
{name:"Shopify",country:"Canada"},
{name:"Performance Food Group",country:"United States"},
{name:"Toho Bank",country:"Japan"},
{name:"First Citizens Bank",country:"United States"},
{name:"Taiwan Business Bank",country:"Taiwan"},
{name:"WPG Holdings",country:"Taiwan"},
{name:"Advanz Pharma",country:"Canada"},
{name:"Tokyu Fudosan",country:"Japan"},
{name:"First Pacific",country:"Hong Kong"},
{name:"Ogaki Kyoritsu Bank",country:"Japan"},
{name:"Vingroup",country:"Vietnam"},
{name:"Ansys",country:"United States"},
{name:"SinoPac Financial",country:"Taiwan"},
{name:"San-In Godo Bank",country:"Japan"},
{name:"Wirecard",country:"Germany"},
{name:"Nanto Bank",country:"Japan"},
{name:"Universal Entertainment",country:"Japan"},
{name:"Mirvac Group",country:"Australia"},
{name:"Grupo Bolivar",country:"Colombia"},
{name:"Constellation Software",country:"Canada"},
{name:"Albemarle",country:"United States"},
{name:"Bank of Xi'an",country:"China"},
{name:"Adient",country:"Ireland"},
{name:"Zain",country:"Kuwait"},
{name:"IDEXX Laboratories",country:"United States"},
{name:"Sansteel Minguang",country:"China"},
{name:"RMB Holdings",country:"South Africa"},
{name:"Bendigo & Adelaide Bank",country:"Australia"},
{name:"Aozora Bank",country:"Japan"},
{name:"Red Star Macalline Group",country:"China"},
{name:"Central Bank of India",country:"India"},
{name:"Founder Securities",country:"China"},
{name:"Vietin Bank",country:"Vietnam"},
{name:"Senshu Ikeda Holdings",country:"Japan"},
{name:"Syndicate Bank",country:"India"},
{name:"Celltrion",country:"South Korea"},
{name:"Inventec",country:"Taiwan"},
{name:"Orient",country:"Japan"},
{name:"Credito Emiliano",country:"Italy"},
{name:"SDIC Capital",country:"China"},
{name:"Indiabulls Housing Finance",country:"India"},
{name:"Tokyo Kiraboshi Financial Group",country:"Japan"},
{name:"Aareal Bank",country:"Germany"},
{name:"Sembcorp Industries",country:"Singapore"},
{name:"China Zhongwang Holdings",country:"China"},
{name:"PacWest Bancorp",country:"United States"},
{name:"Palo Alto Networks",country:"United States"},
{name:"NH Investment & Securities",country:"South Korea"},
{name:"SBA Communications",country:"United States"},
{name:"Hyatt Hotels",country:"United States"},
{name:"Tenneco",country:"United States"},
{name:"Core-Mark Holding",country:"United States"},
{name:"Vodafone Idea",country:"India"},
{name:"MercadoLibre",country:"Argentina"},
{name:"Adyen",country:"Netherlands"},
{name:"Hanesbrands",country:"United States"},
{name:"Longi Green Energy Technology",country:"China"},
{name:"Barry Callebaut",country:"Switzerland"},
{name:"Axiata Group",country:"Malaysia"},
{name:"Banca Popolare di Sondrio",country:"Italy"},
{name:"Liberty Broadband",country:"United States"},
{name:"Suzano Papel e Celulose",country:"Brazil"},
{name:"China Oriental Group",country:"Hong Kong"},
{name:"Sinotrans Ltd.",country:"China"},
{name:"Berry Global Group",country:"United States"},
{name:"President Chain Store",country:"Taiwan"},
{name:"Juniper Networks",country:"United States"},
{name:"Canadian Utilities",country:"Canada"},
{name:"CSPC Pharmaceutical Group",country:"Hong Kong"},
{name:"Broadridge Financial",country:"United States"},
{name:"Chipotle Mexican Grill",country:"United States"},
{name:"Navistar International",country:"United States"},
{name:"Bank of Qingdao",country:"China"},
{name:"China Railway Signal & Communication",country:"China"},
{name:"Liberbank",country:"Spain"},
{name:"Nuernberger Beteiligungs",country:"Germany"},
{name:"Sofina",country:"Belgium"},
{name:"Yes Bank",country:"India"},
{name:"Muyuan Foodstuff",country:"China"},
{name:"Bank of Jiujiang",country:"China"},
{name:"China Development Bank Financial Leasing",country:"China"},
{name:"United Utilities",country:"United Kingdom"},
{name:"JTEKT",country:"Japan"},
{name:"Keiyo Bank",country:"Japan"},
{name:"Basler Kantonalbank",country:"Switzerland"},
{name:"Japan Securities",country:"Japan"},
{name:"Commercial International Bank",country:"Egypt"},
{name:"Alfa Laval",country:"Sweden"},
{name:"China Merchants Expressway Network & Technology Holdings",country:"China"},
{name:"Hyakujushi Bank",country:"Japan"},
{name:"Commerce Bank",country:"United States"},
{name:"Dali Foods Group",country:"China"},
{name:"Financial Street Holdings",country:"China"},
{name:"Hokkoku Bank",country:"Japan"},
{name:"Asian Paints",country:"India"},
{name:"Haidilao International Holding",country:"China"},
{name:"Old Republic International",country:"United States"},
{name:"Oshkosh",country:"United States"},
{name:"Cemig",country:"Brazil"},
{name:"Credit Bank of Moscow",country:"Russia"},
{name:"Fangda Carbon New Material",country:"China"},
{name:"Yamada Denki",country:"Japan"},
{name:"Hengyi Petrochemical Co., Ltd.",country:"China"},
{name:"Xinhu Zhongbao",country:"China"},
{name:"Jaccs",country:"Japan"},
{name:"Zalando",country:"Germany"},
{name:"Informa plc",country:"United Kingdom"},
{name:"Garrett Motion",country:"Switzerland"},
{name:"Medical Properties Trust",country:"United States"},
{name:"Nanya Technology",country:"Taiwan"},
{name:"Sydney Airport",country:"Australia"},
{name:"Kiyo Bank",country:"Japan"},
{name:"International Flavors & Fragrances",country:"United States"},
{name:"JB Financial Group",country:"South Korea"},
{name:"Smurfit Kappa Group",country:"Ireland"},
{name:"Fraport",country:"Germany"},
{name:"Piramal Enterprises",country:"India"},
{name:"Banque Centrale Populaire",country:"Morocco"},
{name:"FMC",country:"United States"},
{name:"Konica Minolta Business Solutions",country:"Japan"},
{name:"Sonova Holding",country:"Switzerland"},
{name:"F.N.B.",country:"United States"},
{name:"Fibra Uno",country:"Mexico"},
{name:"Lotte",country:"South Korea"},
{name:"Musashino Bank",country:"Japan"},
{name:"Migdal Insurance",country:"Israel"},
{name:"Chimera Investment",country:"United States"},
{name:"Sabesp",country:"Brazil"},
{name:"Shanghai Ganglian E-Commerce Holdings",country:"China"},
{name:"EFG International",country:"Switzerland"},
{name:"Cleveland-cliffs",country:"United States"},
{name:"Saudi Arabian Fertilizers",country:"Saudi Arabia"},
{name:"Splunk",country:"United States"},
{name:"Lendlease Group",country:"Australia"},
{name:"Murphy USA",country:"United States"},
{name:"Yageo Corporation",country:"Taiwan"},
{name:"Bureau Veritas",country:"France"},
{name:"Saipem",country:"Italy"},
{name:"United Natural Foods,",country:"United States"},
{name:"Luzerner Kantonalbank",country:"Switzerland"},
{name:"AU Optronics",country:"Taiwan"},
{name:"Marks & Spencer",country:"United Kingdom"},
{name:"Dixons Carphone",country:"United Kingdom"},
{name:"Shoprite Holdings",country:"South Africa"},
{name:"Unisplendour",country:"China"},
{name:"Veeva Systems",country:"United States"},
{name:"Allahabad Bank",country:"India"},
{name:"Credit Acceptance",country:"United States"},
{name:"BBVA Banco Continental",country:"Peru"},
{name:"Indian Bank",country:"India"},
{name:"China Agri-Industries",country:"Hong Kong"},
{name:"Owens Corning",country:"United States"},
{name:"LiveRamp Holdings",country:"United States"},
{name:"Royal Mail",country:"United Kingdom"},
{name:"Cadence Design",country:"United States"},
{name:"Makita",country:"Japan"},
{name:"Nanjing Iron & Steel",country:"China"},
{name:"United Aircraft",country:"Russia"},
{name:"Extra Space Storage",country:"United States"},
{name:"Ipsen",country:"France"},
{name:"Zebra Technologies",country:"United States"},
{name:"H Lundbeck",country:"Denmark"},
{name:"Andhra Bank",country:"India"},
{name:"Bank of Queensland",country:"Australia"},
{name:"Air Lease",country:"United States"},
{name:"Ronshine China Holdings",country:"China"},
{name:"AmBank Group",country:"Malaysia"},
{name:"Prysmian",country:"Italy"},
{name:"VEON",country:"Netherlands"},
{name:"San ju San Financial Group",country:"Japan"},
{name:"Zhejiang Chint Electrics",country:"China"},
{name:"Autoliv",country:"Sweden"},
{name:"Sensata Technologies Holding",country:"United Kingdom"},
{name:"CoStar Group",country:"United States"},
{name:"EasyJet",country:"United Kingdom"},
{name:"Sears Holdings",country:"United States"},
{name:"Western Alliance Bancorp.",country:"United States"},
{name:"Meritz Securities",country:"South Korea"},
{name:"Cimarex Energy",country:"United States"},
{name:"VICI Properties",country:"United States"},
{name:"FIBI Holdings",country:"Israel"},
{name:"Oriental Bank of Commerce",country:"India"},
{name:"BJ's Wholesale Club",country:"United States"},
{name:"Bank of Nagoya",country:"Japan"},
{name:"Grupo De Inversiones Suramericana",country:"Colombia"},
{name:"CPI Property Group.",country:"Luxembourg"},
{name:"IBERIABANK",country:"United States"},
{name:"Sino Land",country:"Hong Kong"},
{name:"China Petroleum Engineering",country:"China"},
{name:"Nomura Research Institute",country:"Japan"},
{name:"Nippon Paint",country:"Japan"},
{name:"Thomas Cook Group",country:"United Kingdom"},
{name:"Tomony Holdings",country:"Japan"},
{name:"Isetan Mitsukoshi Holdings",country:"Japan"},
{name:"Toyota Boshoku",country:"Japan"},
{name:"Want Want China",country:"China"},
{name:"F5 Networks",country:"United States"},
{name:"Innolux",country:"Taiwan"},
{name:"Vipshop Holdings",country:"China"},
{name:"Keysight Technologies",country:"United States"},
{name:"iQIYI",country:"China"},
{name:"Tongling Nonferrous Metals",country:"China"},
{name:"Laurentian Bank",country:"Canada"},
{name:"Ramsay Health Care",country:"Australia"},
{name:"Hero Motocorp",country:"India"},
{name:"Samsung Securities",country:"South Korea"},
{name:"SK Networks",country:"South Korea"},
{name:"Yuexiu Property Co.",country:"Hong Kong"},
{name:"Synnex Technology Intl",country:"Taiwan"},
{name:"Li & Fung",country:"Hong Kong"},
{name:"Jointown Pharmaceutical Group",country:"China"},
{name:"Kuwait Projects",country:"Kuwait"},
{name:"Land Securities Group",country:"United Kingdom"},
{name:"Lyft",country:"United States"},
{name:"Corporation Bank",country:"India"},
{name:"Sunny Optical Technology Group",country:"China"},
{name:"Delek Group",country:"Israel"},
{name:"Sichuan Changhong Electric",country:"China"},
{name:"Wintrust Financial",country:"United States"},
{name:"Indian Overseas Bank",country:"India"},
{name:"RusHydro",country:"Russia"},
{name:"AAC Technologies Holdings",country:"China"},
{name:"Associated Banc-Corp",country:"United States"},
{name:"Burberry Group",country:"United Kingdom"},
{name:"Catcher Technology",country:"Taiwan"},
{name:"Zenith Bank",country:"Nigeria"},
{name:"Grupo Carso",country:"Mexico"},
{name:"Marvell Technology Group",country:"Bermuda"},
{name:"St. Galler Kantonalbank",country:"Switzerland"},
{name:"Lundbergs",country:"Sweden"},
{name:"Sumec Corporation",country:"China"},
{name:"Berkeley Group Holdings",country:"United Kingdom"},
{name:"Inchcape",country:"United Kingdom"},
{name:"Asustek Computer",country:"Taiwan"},
{name:"Digital China Group",country:"China"},
{name:"ISS",country:"Denmark"},
{name:"AVIC International Holdings",country:"China"},
{name:"Goldcorp",country:"Canada"},
{name:"Booz Allen Hamilton Holding",country:"United States"},
{name:"Drilling Company of 1972",country:"Denmark"},
{name:"Canadian Apartment Properties Real Estate Investment Trust",country:"Canada"},
{name:"Kesko",country:"Finland"},
{name:"Securitas",country:"Sweden"},
{name:"Bid",country:"South Africa"},
{name:"Lanxess",country:"Germany"},
{name:"Nippon Paper Industries",country:"Japan"},
{name:"CBOE Global Markets",country:"United States"},
{name:"Saras",country:"Italy"},
{name:"Daily Mail & General Trust",country:"United Kingdom"},
{name:"Mitsubishi Gas Chemical Company,",country:"Japan"},
{name:"Thanachart Capital",country:"Thailand"},
{name:"Korea Zinc",country:"South Korea"},
{name:"Bank OZK",country:"United States"},
{name:"Grupa LOTOS",country:"Poland"},
{name:"Snap",country:"United States"},
{name:"Taiwan Cement",country:"Taiwan"},
{name:"TP ICAP",country:"United Kingdom"},
{name:"IDEX",country:"United States"},
{name:"Thai Oil",country:"Thailand"},
{name:"Bed Bath & Beyond",country:"United States"},
{name:"Incyte",country:"United States"},
{name:"Fuyo General Lease",country:"Japan"},
{name:"JC Penney",country:"United States"}
]
chrome.storage.local.set({'companies':companies});
